# EE569 Homework Assignment #3
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 1 Nov 2015
# Compiled on Mac with g++

all:
	g++ -o run main_dithering.cpp
	@echo "compiling the code for dithering digital half toning"
	@echo "usage : ./run inputImageName inputImageName inputImageName inputImageName outputImageName"
	@echo "example : ./run mandrill.raw ditheredMandrillI4.raw ditheredMandrillI8.raw ditheredMandrillGrayI4.raw ditheredMandrillGrayI8.raw"
	@echo "ENTER YOUR COMMAND WITH THE HELP OF THE ABOVE EXAMPLE"
