# EE569 Homework Assignment #3
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 1 Nov 2015
# Compiled on Mac with g++

all:
	g++ -o run main_errorDiffusion.cpp
	@echo "compiling the code for error Diffusion halftoning"
	@echo "usage : ./run inputImageName outputImageName outputImageName outputImageName"
	@echo "example : ./run mandrill.raw FloydErrorMandrill.raw JJNErrorMandrill.raw StuckiErrorMandrill.raw"
	@echo "ENTER YOUR COMMAND WITH THE HELP OF THE ABOVE EXAMPLE"
