# EE569 Homework Assignment #3
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 1 Nov 2015
# Compiled on Mac with g++

all:
	g++ -o run main_3Dto2D.cpp
	@echo "compiling the code for 3D to 2D image capture"
	@echo "usage : ./run inputImageName inputImageName inputImageName inputImageName inputImageName outputImageName"
	@echo "example : ./run baby.raw baby_cat.raw baby_dog.raw baby_panda.raw baby_bear.raw final2Dimage.raw"
	@echo "ENTER YOUR COMMAND WITH THE HELP OF THE ABOVE EXAMPLE"
